import { createFileRoute } from "@tanstack/react-router";
import { StaticPage } from "@/components/site/StaticPage";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [{ title: "Terms of Service — ToolHub Pro" }, { name: "description", content: "Terms of use for ToolHub Pro." }, { property: "og:url", content: "/terms" }],
    links: [{ rel: "canonical", href: "/terms" }],
  }),
  component: () => (
    <StaticPage title="Terms of Service" updated="July 2026">
      <p>By using ToolHub Pro you agree to these terms. If you do not agree, please do not use the site.</p>
      <h2 className="text-lg font-semibold text-foreground">Use of Service</h2>
      <p>ToolHub Pro provides free browser-based tools "as is" without warranty of any kind. You are responsible for verifying the accuracy of any output before relying on it, especially for financial, medical or legal decisions.</p>
      <h2 className="text-lg font-semibold text-foreground">Acceptable Use</h2>
      <p>You agree not to abuse the service, attempt to disrupt it, or use it for any unlawful purpose.</p>
      <h2 className="text-lg font-semibold text-foreground">Intellectual Property</h2>
      <p>All code, design and branding on ToolHub Pro are owned by us or our licensors. Content generated by you using our tools remains yours.</p>
      <h2 className="text-lg font-semibold text-foreground">Limitation of Liability</h2>
      <p>We are not liable for any losses arising from your use of ToolHub Pro. Use at your own risk.</p>
      <h2 className="text-lg font-semibold text-foreground">Changes</h2>
      <p>We may update these terms at any time. Continued use of the site constitutes acceptance of the updated terms.</p>
    </StaticPage>
  ),
});
